/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ReferenceRouteImport } from "./routes/reference"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as GeneratorRouteImport } from "./routes/generator"
import { Route as IndexRouteImport } from "./routes/index"

const ReferenceRoute = ReferenceRouteImport.update({
  id: "/reference",
  path: "/reference",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: "/generator",
  path: "/generator",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/generator": typeof GeneratorRoute
  "/privacy": typeof PrivacyRoute
  "/reference": typeof ReferenceRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/generator": typeof GeneratorRoute
  "/privacy": typeof PrivacyRoute
  "/reference": typeof ReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/generator": typeof GeneratorRoute
  "/privacy": typeof PrivacyRoute
  "/reference": typeof ReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/generator" | "/privacy" | "/reference"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/generator" | "/privacy" | "/reference"
  id: "__root__" | "/" | "/generator" | "/privacy" | "/reference"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratorRoute: typeof GeneratorRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferenceRoute: typeof ReferenceRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/reference": {
      id: "/reference"
      path: "/reference"
      fullPath: "/reference"
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/generator": {
      id: "/generator"
      path: "/generator"
      fullPath: "/generator"
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratorRoute: GeneratorRoute,
  PrivacyRoute: PrivacyRoute,
  ReferenceRoute: ReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
